"""empty message

Revision ID: abcbeba1cdab
Revises: 8e1e8be7e4f5
Create Date: 2023-03-08 12:51:12.991077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abcbeba1cdab'
down_revision = '8e1e8be7e4f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=45), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('workout',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('Time', sa.String(length=50), nullable=False),
    sa.Column('Location', sa.String(length=50), nullable=False),
    sa.Column('Muscle', sa.String(length=50), nullable=False),
    sa.Column('Equipment', sa.String(length=50), nullable=False),
    sa.Column('key', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('Equipment'),
    sa.UniqueConstraint('Location'),
    sa.UniqueConstraint('Muscle'),
    sa.UniqueConstraint('Time'),
    sa.UniqueConstraint('key')
    )
    op.create_table('my__workout',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Workout_name', sa.String(length=200), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['Workout_name'], ['workout.key'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('my__workout')
    op.drop_table('workout')
    op.drop_table('user')
    # ### end Alembic commands ###
